# Netlify Configuration for React App
[build]
  # Directory where the build command will run
  base = "/"
  
  # Build command
  command = "yarn build"
  
  # Directory with built files to deploy
  publish = "build"

[build.environment]
  # Node.js version - Updated to 20 for Firebase compatibility
  NODE_VERSION = "20"
  
  # Yarn version
  YARN_VERSION = "1.22.22"

# Configure secrets scanning to allow Firebase configuration variables
# These are client-side public configuration values, not sensitive secrets
[template.environment]
  SECRETS_SCAN_OMIT_KEYS = "REACT_APP_FIREBASE_API_KEY,REACT_APP_FIREBASE_AUTH_DOMAIN,REACT_APP_FIREBASE_PROJECT_ID,REACT_APP_FIREBASE_STORAGE_BUCKET,REACT_APP_FIREBASE_MESSAGING_SENDER_ID,REACT_APP_FIREBASE_APP_ID,REACT_APP_FIREBASE_MEASUREMENT_ID"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
